django15/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from cms import views

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/', include('allauth.urls')),
                       url(r'^$', 'cms.views.upload_file'),
                       url(r'^employee/$', 'cms.views.list'),
                       url(r'^report/$', 'cms.views.report'),
                       url(r'^export/$', 'cms.views.export'),
                       )

cms/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models


class Whatever(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.title

FOOD_TYPE = (
    ("Lunch", _("Lunch")),
    ("Dinner", _("Dinner")),
)

class Employee(models.Model):
	employee_id 	= models.CharField(max_length=200, null=True, blank=True)
	employee_name	= models.CharField(max_length=200, null=True, blank=True)
	email			= models.EmailField(null=True, blank=True)
	contact_number	= models.BigIntegerField(null=True, blank=True)

	def __unicode__(self):
		return self.employee_id + " -  " + self.employee_name

class Food(models.Model):
	employee 		= models.ForeignKey(Employee, null=True, blank=True)
	type			= models.CharField(choices=FOOD_TYPE,max_length=200, null=True, blank=True)
	avail_datetime	= models.DateTimeField(null=True, blank=True)

	def __unicode__(self):
		return self.employee.employee_id


class FoodAll(models.Model):
	employee 		= models.ForeignKey(Employee, null=True, blank=True)
	type			= models.CharField(choices=FOOD_TYPE,max_length=200, null=True, blank=True)
	avail_datetime	= models.DateTimeField(null=True, blank=True)

	def __unicode__(self):
		return self.employee.employee_id

cms/forms.py
from django import forms
from models import Whatever

class UploadFileForm(forms.Form):
	file = forms.FileField()

cms/views.py
from django.shortcuts import render_to_response, render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from cms.models import Whatever
from cms.forms import UploadFileForm
from cms.models import Employee, Food, FoodAll
from django.core.context_processors import csrf
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect

import sys
import pandas as pd
import csv
import os
import dateutil.parser

@login_required
def upload_file(request):
	if request.method == "POST":
		file = request.FILES['file']
		# print request.FILES['file']
		file = os.path.join(os.path.dirname(__file__), 'employee.csv')

		# with open(file, 'rb') as csvfile:
		# 	spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
		# 	for row in spamreader:
		# 		try:
		# 			emp_min =  row[0].split(",")
		# 			emp_id = emp_min[0]
		# 			emp_name = emp_min[1]+" "+ row[1].split(",")[0]
		# 			emp_email = row[1].split(",")[1]
		# 			try:
		# 				employee = Employee.objects.get(employee_id=emp_id)
		# 			except:
		# 				employee = Employee(employee_id=emp_id, employee_name=emp_name, email=emp_email)
		# 				employee.save()
		# 		except:
		# 			pass

		emppp = Food.objects.all().delete()
		data = pd.read_csv(request.FILES['file'])  # you can also add params such as header, sep etc.
		array = data.values
		# print array
		datadict = []
		for i in array:
			col1 = i[0].split()
			# print i[0], "***"
			# print col1, "$$$$"
			hsw = col1[1].split("/")
			hsd = hsw[1]+"/"+hsw[0]+"/"+hsw[2]
			st_str = hsd + " " + col1[2]
			# print st_str, "=+================="
			hrs = col1[2].split(":")[0]
			if int(hrs)>17:
				type = "Dinner"
			else:
				type = "Lunch"
			dt = dateutil.parser.parse(st_str)
			# print dt
			# print dt
			try:
				emp = Employee.objects.get(employee_id=col1[0])
				try:
					food = Food.objects.get(employee=emp, type=type, avail_datetime=dt)
				except:
					food = Food(employee=emp, type=type, avail_datetime=dt)
					food.save()

				try:
					foodall = FoodAll.objects.get(employee=emp, type=type, avail_datetime=dt)
				except:
					food = FoodAll(employee=emp, type=type, avail_datetime=dt)
					food.save()
			except:
				pass
			ad = {}
			i = i[0].split(" ")
			ad[i[0]] = i[6], i[7]
			datadict.append(ad)
		return redirect('/report/')

		# merged = {}
		# for d in datadict:
		# 	for k, v in d.items():
		# 		if k not in merged: merged[k] = []
		# 		merged[k].append(v)
        #
		# # final = {}
		# # for k, v in merged.items ():
		# # 	final[k] = len(v)
        #
        #
        #
		# for k, v in merged.items():
		# 	merged[k].insert(0, len(v))
        #
		# # print merged
        #
		# myfile = open('finaldata.csv', 'wb')
		# wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
		# wr.writerow(["Employee ID", "No of Lunch/Dinner", "Lunch", "Dinner"])
		# for k, v in merged.items():
		# 	merged[k].insert(0, k)
		# 	smdata = []
		# 	for i in merged[k]:
		# 		if type(i) is tuple:
		# 			smdata.append(int(i[1].split(":")[0]))
		# 	if smdata:
		# 		lunch = sum(i < 17 for i in smdata)
		# 		dinner = sum(i > 17 for i in smdata)
		# 		merged[k].insert(2, lunch)
		# 		merged[k].insert(3, dinner)
		# 	wr.writerow(merged[k])


	form = UploadFileForm()
	return render(request, 'index.html',{"form":form})

def list(request):
	empdata = Employee.objects.all()
	form = UploadFileForm()
	if request.method == "POST":
		data = pd.read_csv(request.FILES['file'])  # you can also add params such as header, sep etc.
		array = data.values
		for one in array:
			try:
				emp = Employee.objects.get(employee_id=one[0])
			except:
				emp = Employee(employee_id=one[0], employee_name=one[1], email = one[2])
				emp.save()
	return render(request, 'cms/list.html',{"emp":empdata, "form":form})

def report(request):
	emp_id = Employee.objects.all()
	data = {}
	month = ""
	year = ""
	for emp in emp_id:
		emp_data = []
		emp_food = Food.objects.filter(employee=emp)
		# year = emp_food[0].avail_datetime.strftime('%Y')
		# print year, "&&&&&&&&&&&"
		lunch = 0
		dinner = 0
		total = 0
		for i in emp_food:
			month = i.avail_datetime.strftime('%B')
			year = i.avail_datetime.strftime('%Y')
			total = total + 1
			# print i.avail_datetime.strftime('%B'), i.avail_datetime, "-------"
			if i.avail_datetime.hour >= 5:
				lunch = lunch + 1
			else:
				dinner = dinner + 1
		# emp_data.append(emp)
		emp_data.append(lunch)
		emp_data.append(dinner)
		emp_data.append(total)
		emp_data.append(emp_food)
		data[emp] = emp_data
	date =  month + " "+ year
	return render(request, 'cms/report.html',{"month":month, "food":data, "date":date})


def export(request):
	emp_id = Employee.objects.all()
	data = {}
	month = ""

	for emp in emp_id:
		abd = []
		emp_data = []
		emp_food = Food.objects.filter(employee=emp)
		emp_food_data = Food.objects.filter(employee=emp).values_list('avail_datetime', flat=True)

		for i in emp_food_data:
			abd.append(str(i.date()))
		abc = "  ||  ".join(abd)
		# print abc
		lunch = 0
		dinner = 0
		total = 0
		for i in emp_food:
			month = i.avail_datetime.strftime('%B')
			total = total + 1
			# print i.avail_datetime.strftime('%B'), i.avail_datetime, "-------"
			if i.avail_datetime.hour >= 5:
				lunch = lunch + 1
			else:
				dinner = dinner + 1
		# emp_data.append(emp)
		emp_data.append(lunch)
		emp_data.append(dinner)
		emp_data.append(total)
		emp_data.append(abc)
		data[emp] = emp_data

	# Create the HttpResponse object with the appropriate CSV header.
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="data.csv"'
	writer = csv.writer(response)
	writer.writerow(['Employee ID', 'Name', 'Lunch', 'Dinner', 'Total','Dates'])
	for key in data:
		writer.writerow([key.employee_id, key.employee_name, data[key][0], data[key][1], data[key][2], data[key][3]])

	return response

templates/add.html
{% extends "base.html" %}


{% block content %}

<form action="/add/" method="post" enctype="multipart/form-data">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input id ="submit" type="submit" name="submit" value="Create Whatever">
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<!-- saved from url=(0050)http://getbootstrap.com/examples/navbar-fixed-top/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/img/Final_logo.png">

    <title>Fixed Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/static/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
    <link href="/static/css/custom.css" rel="stylesheet">
<!-- Latest compiled and minified JavaScript -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.min.js"></script>
{#    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>#}
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  <script src="/static/js/jasny-bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand-custom" href="/"><img src="/static/img/Final_logo.png" width="150" height="40" style="margin-top: 0px!important;"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
            <li id="home" class="active"><a href="/">Home</a></li>
            <li id="list"><a href="/employee/">Employee</a></li>
            <li id="report"><a href="/report/">Food</a></li>
{#            <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#about">About</a></li>#}
{#            <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#contact">Contact</a></li>#}

          </ul>
        {% endif %}
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Profile</a></li>
                <li><a href="/accounts/logout/">Logout</a></li>
{#                <li role="separator" class="divider"></li>#}
{#                <li class="dropdown-header">Nav header</li>#}
{#                <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">Separated link</a></li>#}
{#                <li><a href="http://getbootstrap.com/examples/navbar-fixed-top/#">One more separated link</a></li>#}
              </ul>
            </li>
            {% else %}
                <li><a href="/accounts/login/">Login</a></li>
          {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- Main component for a primary marketing message or call to action -->


        {% block content %}
        {% endblock %}




    </div> <!-- /container -->

</body></html>

templates/cms/list.html
{% extends "base.html" %}

{% block content %}
    {% include 'cms/models.html' %}
    <div class="add-emp-div">
            <span class="btn-add-emp"><button class="btn btn-info" data-toggle="modal" data-target="#myModal">Add Employee</button></span>
    </div>
    <table id="table_id" class="display table table-striped">
    <thead>
        <tr>
            <th>Employee Id</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
    {% for em in emp %}
        <tr>
            <td>{{ em.employee_id }}</td>
            <td>{{ em.employee_name }}</td>
            <td>{{ em.email }}</td>
        </tr>
   {% endfor %}
    </tbody>
</table>
<script>
$(document).ready( function () {
    $('#home').removeClass("active");
    $('#report').removeClass("active");
    $('#list').addClass("active");

    $('#table_id').dataTable( {
                            "pageLength": 25
                            } );

} );
</script>
{% endblock %}

templates/cms/models.html
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
    <div class="jumbotron">
        <h3>Upload File</h3>
        <form action="." method="post" enctype="multipart/form-data" id="main_form_id">{% csrf_token %}
{#            {{ form.as_p }}#}
{#            <p><label for="id_file">Upload File:</label> <input id="id_file" name="file" type="file"></p>#}

            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput"><i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>
  <span class="input-group-addon btn btn-default btn-file"><span class="fileinput-new">Select file</span><span class="fileinput-exists">Change</span><input type="file" name="file" id="id_file"></span>
  <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
</div>

            <input type="submit" align="center" style="margin-left: 45%;" class="btn btn-info" value="Submit">
        </form>

    </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
{#        <button type="button" class="btn btn-primary">Save changes</button>#}
      </div>
    </div>
  </div>
</div>

templates/cms/report.html
{% extends "base.html" %}

{% block content %}

    {% include 'cms/models.html' %}

    <h4 align="center"><strong>{{ date }}</strong></h4>
    <div class="add-emp-div">
        <span class="btn-add-emp"><a href="/export/" class="btn btn-warning">Export to CSV</a></span>
    </div>
    <table id="table_id" class="display table">
        <thead>

        <tr>
            <th>Employee Id</th>
            <th>Name</th>
            <th>Lunch</th>
            <th>Dinner</th>
            <th>Total</th>
            {#            <th>Dates</th>#}
        </tr>
        </thead>
        <tbody>
        {% for key, values in food.items %}
            {% if not values.2 == 0 %}

                <tr>
                    <td data-toggle="modal" data-target="#{{ key.employee_id }}"
                        style="cursor:pointer">{{ key.employee_id }}</td>
                    <td>{{ key.employee_name }}</td>
                    <td>{{ values.0 }}</td>
                    <td>{{ values.1 }}</td>
                    <td>{{ values.2 }}</td>


                    <!-- Modal -->
                    <div class="modal fade" id="{{ key.employee_id }}" tabindex="-1" role="dialog"
                         aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                            aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">{{ key.employee_name }}</h4>
                                </div>
                                <div class="modal-body">


                                    <div class="row">

                                        {% for dt in values.3 %}
                                            <div class="col-lg-3">
                                                <p>{{ dt.avail_datetime.date }}</p>
                                            </div>
                                        {% endfor %}
                                    </div>


                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    {#        <button type="button" class="btn btn-primary">Save changes</button>#}
                                </div>
                            </div>
                        </div>
                    </div>

                </tr>

            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <script>
        $(document).ready(function () {
            $('#home').removeClass("active");
            $('#list').removeClass("active");
            $('#report').addClass("active");

            $('#table_id').dataTable({
                "pageLength": 100
            });

        });
    </script>
{% endblock %}

templates/index.html
{% extends "base.html" %}


{% block content %}

    <div class="jumbotron">
        <h3>Upload File</h3>
        <form action="/" method="post" enctype="multipart/form-data" id="main_form_id">{% csrf_token %}
{#            {{ form.as_p }}#}
{#            <p><label for="id_file">Upload File:</label> <input id="id_file" name="file" type="file"></p>#}

            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput"><i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>
  <span class="input-group-addon btn btn-default btn-file"><span class="fileinput-new">Select file</span><span class="fileinput-exists">Change</span><input type="file" name="file" id="id_file"></span>
  <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
</div>

            <input type="submit" align="center" style="margin-left: 45%;" class="btn btn-info" value="Submit">
        </form>

    </div>

{% endblock %}